# Generated by Django 3.1 on 2021-02-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companydb',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='curr_del',
            fields=[
                ('del_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=40)),
                ('cust_add', models.CharField(max_length=200)),
                ('cust_contact', models.BigIntegerField()),
                ('order_cap', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
                ('cmp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydb')),
            ],
        ),
    ]
