# Generated by Django 3.1 on 2021-02-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_del', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('cmp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydb')),
            ],
        ),
    ]
