# Generated by Django 3.1 on 2021-02-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delivery_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_data',
            name='date',
        ),
        migrations.AddField(
            model_name='delivery_data',
            name='uploaded_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery_data',
            name='new_del',
            field=models.FileField(upload_to='delivery_data/'),
        ),
    ]
