# Generated by Django 3.1 on 2021-02-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210201_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_log',
            fields=[
                ('del_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=40)),
                ('cust_add', models.CharField(max_length=200)),
                ('cust_contact', models.BigIntegerField()),
                ('del_date', models.DateField()),
                ('cmp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydb')),
            ],
        ),
    ]
