# Generated by Django 3.2.2 on 2021-06-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delivery_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_data',
            name='uploaded_at',
        ),
    ]
