# Generated by Django 3.2.2 on 2021-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_delivery_data_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='delivery_data',
            name='cmp_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
