# Generated by Django 3.2.2 on 2021-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210608_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_data',
            name='data_id',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery_data',
            name='cmp_id',
            field=models.CharField(max_length=10),
        ),
    ]
