# Generated by Django 3.2.2 on 2021-06-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210608_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delivery_data',
        ),
    ]
