# Generated by Django 3.2.2 on 2021-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_delete_delivery_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_data',
            fields=[
                ('data_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cmp_id', models.CharField(max_length=10)),
                ('new_del', models.FileField(upload_to='delivery_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
