# Generated by Django 3.1 on 2021-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_admindb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverexec',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('mob_no', models.BigIntegerField()),
                ('add', models.CharField(max_length=200)),
                ('vehicle_trype', models.IntegerField()),
                ('onleave', models.BooleanField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
