# Generated by Django 3.1 on 2021-02-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_deliverexec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deliverexec',
            new_name='deliveryexec',
        ),
    ]
