# Generated by Django 3.1 on 2021-02-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_auto_20210204_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryexec',
            name='email',
            field=models.CharField(default='ankitkumar11jan@gmail.com', max_length=40),
            preserve_default=False,
        ),
    ]
